import { Agente } from '../hardcodeo/agente';

export const AGENTES: Agente[] = [

      {
          id: 1,
          documento: 31359294,
          nombre: 'Angela Magdalena',
          apellido: 'Cifuentes',
          fechaNacimiento: '12/04/1957',
          edad: 23,
          estado: 'alta',
          situacion: 'profesional',
          foto: 'https://image.shutterstock.com/image-photo/passport-photo-asian-female-natural-260nw-692128333.jpg',
        },
        {
          id: 231,
          documento: 31359294,
          nombre: 'Maria Alejandra',
          apellido: 'Martinez',
          fechaNacimiento: '12/04/1957',
          edad: 23,
          estado: 'alta',
          situacion: 'residente',
          foto: 'https://image.shutterstock.com/image-photo/portrait-laughing-businesswoman-long-dark-260nw-235195312.jpg',
        },
        {
          id: 537,
          documento: 31359294,
          nombre: 'Fernando Gabriel',
          apellido: 'Ferragut',
          fechaNacimiento: '12/04/1957',
          edad: 53,
          estado: 'baja',
          situacion: 'comision de servicio',
          foto: 'https://image.shutterstock.com/image-photo/photo-document-passport-id-mature-260nw-1178817271.jpg',
        },
        {
          id: 642,
          documento: 31359294,
          nombre: 'Lautaro Miguel',
          apellido: 'Fernandez',
          fechaNacimiento: '12/04/1957',
          edad: 23,
          estado: 'alta',
          situacion: 'profesional',
          foto: 'https://image.shutterstock.com/image-photo/passport-picture-cool-guy-blue-260nw-288530261.jpg',
        },
        {
          id: 725,
          documento: 31359294,
          nombre : 'Mariela Macarena',
          apellido: 'Tamarini',
          fechaNacimiento: '12/04/1957',
          edad: 76,
          estado: 'alta',
          situacion: 'tecnico',
          foto: 'https://image.shutterstock.com/image-photo/passport-picture-smiling-turkish-businesswoman-260nw-274128659.jpg',
        },
        {
          id: 346,
          documento: 31359294,
          nombre : 'Patricia Alejandra',
          apellido: 'Hernandez',
          fechaNacimiento: '12/04/1957',
          edad: 76,
          estado: 'alta',
          situacion: 'tecnico',
          foto: 'https://image.shutterstock.com/image-photo/passport-picture-asian-young-woman-260nw-1016732269.jpg',
        },
        {
          id: 358,
          documento: 31359294,
          nombre : 'Carlos Ramiro',
          apellido: 'Balmaceda',
          fechaNacimiento: '12/04/1957',
          edad: 76,
          estado: 'alta',
          situacion: 'tecnico',
          foto: 'https://image.shutterstock.com/image-photo/face-close-portrait-like-mug-260nw-382306927.jpg',
        }
      ];