import { Agente } from '../hardcodeo/agente';

export const AGENTES: Agente[] = [

      {
          id: 1,
          documento: 31359294,
          cuil: 20313592945,
          nombre: 'Angela Magdalena',
          apellido: 'Cifuentes',
          fechaNacimiento: '12/04/1957',
          edad: 23,
          sexo: 'Femenino',
          domicilio: 'General San Martin 892',
          departamento: '5B',
          estado: 'alta',
          situacion: 'profesional',
          nivel: 'terciario',
          titulo: 'bachiller',
          fechaIngresoEstado: '07/11/1996',
          fechaIngresoHospital: '21/12/1996',
          antiguedad: 32,
          tipoNorma: '45B',
          numeroNorma: 421,
          fechaNorma: '23/03/2000',
          agrupamientoNorma: 'agrupamiento',
          categoria: 'P40',
          funcion: 'Tecnico en Seguridad e Higiene',
          lugarTrabajo: 'Laboratorio',
          dependencia: 'Hemoterapia',
          horario: '8 - 12 hs',
          jornada: 'string',
          dedicacion: 'string',
          tiempoPleno: 'string',
          activas: false,
          pasivas: true,
          foto: 'https://image.shutterstock.com/image-photo/passport-photo-asian-female-natural-260nw-692128333.jpg',
        },
        {
          id: 231,
          documento: 31359294,
          cuil: 20313592945,
          nombre: 'Maria Alejandra',
          apellido: 'Martinez',
          fechaNacimiento: '12/04/1957',
          edad: 23,
          sexo: 'Femenino',
          domicilio: 'General San Martin 892',
          departamento: '5B',
          estado: 'alta',
          situacion: 'residente',
          nivel: 'terciario',
          titulo: 'bachiller',
          fechaIngresoEstado: '07/11/1996',
          fechaIngresoHospital: '21/12/1996',
          antiguedad: 32,
          tipoNorma: '45B',
          numeroNorma: 421,
          fechaNorma: '23/03/2000',
          agrupamientoNorma: 'agrupamiento',
          categoria: 'P40',
          funcion: 'Tecnico en Seguridad e Higiene',
          lugarTrabajo: 'Laboratorio',
          dependencia: 'Hemoterapia',
          horario: '8 - 12 hs',
          jornada: 'string',
          dedicacion: 'string',
          tiempoPleno: 'string',
          activas: false,
          pasivas: true,
          foto: 'https://image.shutterstock.com/image-photo/portrait-laughing-businesswoman-long-dark-260nw-235195312.jpg',
        },
        {
          id: 537,
          documento: 31359294,
          cuil: 20313592945,
          nombre: 'Fernando Gabriel',
          apellido: 'Ferragut',
          fechaNacimiento: '12/04/1957',
          edad: 53,
          sexo: 'Femenino',
          domicilio: 'General San Martin 892',
          departamento: '5B',
          estado: 'baja',
          situacion: 'comision de servicio',
          nivel: 'terciario',
          titulo: 'bachiller',
          fechaIngresoEstado: '07/11/1996',
          fechaIngresoHospital: '21/12/1996',
          antiguedad: 32,
          tipoNorma: '45B',
          numeroNorma: 421,
          fechaNorma: '23/03/2000',
          agrupamientoNorma: 'agrupamiento',
          categoria: 'P40',
          funcion: 'Tecnico en Seguridad e Higiene',
          lugarTrabajo: 'Laboratorio',
          dependencia: 'Hemoterapia',
          horario: '8 - 12 hs',
          jornada: 'string',
          dedicacion: 'string',
          tiempoPleno: 'string',
          activas: false,
          pasivas: true,
          foto: 'https://image.shutterstock.com/image-photo/photo-document-passport-id-mature-260nw-1178817271.jpg',
        },
        {
          id: 642,
          documento: 31359294,
          cuil: 20313592945,
          nombre: 'Lautaro Miguel',
          apellido: 'Fernandez',
          fechaNacimiento: '12/04/1957',
          edad: 23,
          sexo: 'Femenino',
          domicilio: 'General San Martin 892',
          departamento: '5B',
          estado: 'alta',
          situacion: 'profesional',
          nivel: 'terciario',
          titulo: 'bachiller',
          fechaIngresoEstado: '07/11/1996',
          fechaIngresoHospital: '21/12/1996',
          antiguedad: 32,
          tipoNorma: '45B',
          numeroNorma: 421,
          fechaNorma: '23/03/2000',
          agrupamientoNorma: 'agrupamiento',
          categoria: 'P40',
          funcion: 'Tecnico en Seguridad e Higiene',
          lugarTrabajo: 'Laboratorio',
          dependencia: 'Hemoterapia',
          horario: '8 - 12 hs',
          jornada: 'string',
          dedicacion: 'string',
          tiempoPleno: 'string',
          activas: false,
          pasivas: true,
          foto: 'https://image.shutterstock.com/image-photo/passport-picture-cool-guy-blue-260nw-288530261.jpg',
        },
        {
          id: 725,
          documento: 31359294,
          cuil: 20313592945,
          nombre : 'Mariela Macarena',
          apellido: 'Tamarini',
          fechaNacimiento: '12/04/1957',
          edad: 76,
          sexo: 'Femenino',
          domicilio: 'General San Martin 892',
          departamento: '5B',
          estado: 'alta',
          situacion: 'tecnico',
          nivel: 'terciario',
          titulo: 'bachiller',
          fechaIngresoEstado: '07/11/1996',
          fechaIngresoHospital: '21/12/1996',
          antiguedad: 32,
          tipoNorma: '45B',
          numeroNorma: 421,
          fechaNorma: '23/03/2000',
          agrupamientoNorma: 'agrupamiento',
          categoria: 'P40',
          funcion: 'Tecnico en Seguridad e Higiene',
          lugarTrabajo: 'Laboratorio',
          dependencia: 'Hemoterapia',
          horario: '8 - 12 hs',
          jornada: 'string',
          dedicacion: 'string',
          tiempoPleno: 'string',
          activas: false,
          pasivas: true,
          foto: 'https://image.shutterstock.com/image-photo/passport-picture-smiling-turkish-businesswoman-260nw-274128659.jpg',
        },
        {
          id: 346,
          documento: 31359294,
          cuil: 20313592945,
          nombre : 'Patricia Alejandra',
          apellido: 'Hernandez',
          fechaNacimiento: '12/04/1957',
          edad: 76,
          sexo: 'Femenino',
          domicilio: 'General San Martin 892',
          departamento: '5B',
          estado: 'alta',
          situacion: 'tecnico',
          nivel: 'terciario',
          titulo: 'bachiller',
          fechaIngresoEstado: '07/11/1996',
          fechaIngresoHospital: '21/12/1996',
          antiguedad: 32,
          tipoNorma: '45B',
          numeroNorma: 421,
          fechaNorma: '23/03/2000',
          agrupamientoNorma: 'agrupamiento',
          categoria: 'P40',
          funcion: 'Tecnico en Seguridad e Higiene',
          lugarTrabajo: 'Laboratorio',
          dependencia: 'Hemoterapia',
          horario: '8 - 12 hs',
          jornada: 'string',
          dedicacion: 'string',
          tiempoPleno: 'string',
          activas: false,
          pasivas: true,
          foto: 'https://image.shutterstock.com/image-photo/passport-picture-asian-young-woman-260nw-1016732269.jpg',
        },
        {
          id: 358,
          documento: 31359294,
          cuil: 20313592945,
          nombre : 'Carlos Ramiro',
          apellido: 'Balmaceda',
          fechaNacimiento: '12/04/1957',
          edad: 76,
          sexo: 'Femenino',
          domicilio: 'General San Martin 892',
          departamento: '5B',
          estado: 'alta',
          situacion: 'tecnico',
          nivel: 'terciario',
          titulo: 'bachiller',
          fechaIngresoEstado: '07/11/1996',
          fechaIngresoHospital: '21/12/1996',
          antiguedad: 32,
          tipoNorma: '45B',
          numeroNorma: 421,
          fechaNorma: '23/03/2000',
          agrupamientoNorma: 'agrupamiento',
          categoria: 'P40',
          funcion: 'Tecnico en Seguridad e Higiene',
          lugarTrabajo: 'Laboratorio',
          dependencia: 'Hemoterapia',
          horario: '8 - 12 hs',
          jornada: 'string',
          dedicacion: 'string',
          tiempoPleno: 'string',
          activas: false,
          pasivas: true,
          foto: 'https://image.shutterstock.com/image-photo/face-close-portrait-like-mug-260nw-382306927.jpg',
        }
      ];